const ChatActionTypes = {
    SEND_MESSAGE_START: "SEND_MESSAGE_START",
    SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE"
}

export default ChatActionTypes