const UserActionTypes = {
    CHANGE_USER_NAME_START: 'CHANGE_USER_NAME_START',
    CHANGE_USER_NAME_SUCCESS: 'CHANGE_USER_NAME_SUCCESS',
    CHANGE_USER_NAME_FAILURE: 'CHANGE_USER_NAME_FAILURE',
    INITIALIZE_USER_ID_START:'INITIALIZE_USER_ID_START',
    INITIALIZE_USER_ID_SUCCESS:'INITIALIZE_USER_ID_SUCCESS',
    INITIALIZE_USER_ID_FAILURE:'INITIALIZE_USER_ID_FAILURE',
    USERLIST_UPDATE_START:'USERLIST_UPDATE_START',
    USERLIST_UPDATE_SUCCESS:'USERLIST_UPDATE_SUCCESS',
    USERLIST_UPDATE_FAILURE:'USERLIST_UPDATE_FAILURE',
}

export default UserActionTypes